example <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow=4, ncol=2)
Party <- matrix(c(23, 0, 7, 1, 5), nrow = 10, ncol = 2)
party <- matrix (c(1, 3, 6, 8, 12, 1), nrow = 2, ncol = 3)
BiocManager::install()
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install()
install.packages("devtools")
library(BiocManager)
BiocManager::available()
library(ggplot2)
library(devtools)
package:BiocManager
library(BiocManager)
installed.packages()
install.packages("backports")
detach("package:ggplot2", unload = TRUE)
library(ggplot2)
library(BiocManager)
help(package="ggplot2")
sessionInfo()
version
browseVignettes("ggplot2")
aes()
